### PR TITLE
Add navigation support

### LINKED ISSUE #14: A way for the levelblock to be considered in the backing of Navmesh
This plugin is awesome, the only problem is you can't bake any navmesh on the nodes, which makes it a lot harder to design enemy pathfinding on the nodes, unless you use AStar3D.

See [this thread](https://forum.godotengine.org/t/navmesh-not-generating/91842/3?u=greaven) response for more deatils on adding compatibility for navmesh in the plugin.

### PR DESCRIPTION
**Pull request by OneginIII**
This commit adds navigation support using [this new Godot 4.3 feature](https://github.com/godotengine/godot/pull/90876).

Fixes #14.

### CODE REVIEW

**Comment by Cryszon** [comment]
# TODO

- [ ] Update CHANGELOG
- [ ] Update README to indicate Godot 4.3 requirement, new features (and maybe disparity to Godot 3 version)
- [ ] Tag & create release
- [ ] Submit new version to Asset Library

**Comment by smix8** [comment]
Hi @Cryszon and @OneginIII 

Looks like you have a nice little fanbase for your addon as a few people contacted me about the (new) navmesh baking.

I am a little late to review comment that alreay merged PR but I spotted two potential issues that you may want to address in a patch as they can create  noticeable performance issues for users baking navmesh. I will give you a script example below so it is easier to follow along what I am babbling here.

If I understand this addon right, the `level_block_node.gd` node is the main node used for every single created block. This means we are currently adding a new parser for every single addon node.

It may have not been clear enough from the limited example in the parser PR but the parsers are intended to be create one per addon scope, or in case of a more complex addon with many node classes, one parser per complex class.

The reason is because the parsing process recursivly calls every single registered parser for every parsed node. If you add a few hundred parsers that all do the same it not only bogs down parse performance, but it will also add many geometry duplicates all the time.

So what I suggest is to move the parser register related code to the `EditorPlugin`. Usually those parsers are created inside the `EditorPlugin` `_enter_tree()` function with the parser being deleted again in the `_exit_tree()` function when the addon gets disabled.

Inside the callback function for the parser the 3rd parameter gives you the node that is parsed. Check if that is a node from this addon and ignore everything else. That functions gets called many times for all nodes in the parsing process not just the addon node. Add that geometry for this node to the 2nd parameter source geometry object. You can make this callback function `static` to assure that you do not rely on anything local by accident.

Second issue is that it is adding the geometry by using a visual rendering `Mesh` resource which is very slow. Since the addon already creates procedural mesh faces those faces could be added instead to the navmesh source geometry object which is fast.

The problem with visual `Mesh` resources and why they are so bad for navmesh parse performance is because they do not store their geometry data on the CPU. So everytime that function is called the GPU gets stalled to return the mesh data which creates performance problems for users at runtime.

Here is a basic gdscript example for an addon that wants to add navmesh geometry just for its custom node, including some dummy code for testing that should run when you toggle the addon enabled. If everything works you should print an array with 9 floats.

```gdscript
@tool
extends EditorPlugin

var source_geometry_parser: RID
var source_geometry_parser_callback: Callable


class DummyCustomAddonNode extends Node3D:
	var faces: PackedVector3Array


func _enter_tree() -> void:
	source_geometry_parser_callback = Callable(self, "_on_source_geometry_parser_callback")
	source_geometry_parser = NavigationServer3D.source_geometry_parser_create()
	NavigationServer3D.source_geometry_parser_set_callback(source_geometry_parser, source_geometry_parser_callback)

	_dummy_test_parser()


func _dummy_test_parser():
	var dummy_parse_node = DummyCustomAddonNode.new()
	# Add a triangle face.
	dummy_parse_node.faces = PackedVector3Array([
		Vector3(-1.0, 0.0, 1.0),
		Vector3(1.0, 0.0, 1.0),
		Vector3(1.0, 0.0, -1.0),
	])
	add_child(dummy_parse_node)
	
	var parse_settings: NavigationMesh = NavigationMesh.new()
	var parse_source_geometry: NavigationMeshSourceGeometryData3D = NavigationMeshSourceGeometryData3D.new()
	NavigationServer3D.parse_source_geometry_data(parse_settings, parse_source_geometry, self)
	
	print(parse_source_geometry.get_vertices())


func _exit_tree() -> void:
	NavigationServer3D.free_rid(source_geometry_parser)
	source_geometry_parser = RID()
	source_geometry_parser_callback = Callable()


static func _on_source_geometry_parser_callback(
	p_navigation_mesh: NavigationMesh,
	p_source_geometry_data: NavigationMeshSourceGeometryData3D,
	p_parsed_node: Node) -> void:

	# Add custom source geometry to p_source_geometry_data.
	# The p_navigation_mesh holds the parse settings. Do NOT edit or add directly to p_navigation_mesh.
	# The p_parsed_node is the currently parsed node.

	if not p_parsed_node is DummyCustomAddonNode:
		return

	var xform: Transform3D = p_parsed_node.global_transform
	var faces: PackedVector3Array = p_parsed_node.faces

	p_source_geometry_data.add_faces(faces, xform)

```

**Comment by Cryszon** [comment]
Thank you very much for taking the time to write such a detailed and insightful comment! Refactoring the plugin code shouldn't be a problem, but will obviously take some time. Would it be ok to ask you to review the fix PR once it's done? I also completely understand if you don't have the time or interest in it.

**Comment by smix8** [comment]
@Cryszon Sure I can review it. Just ping me or join the RocketChat Godot dev chat navigation channel and ask about it. I usally look at the channel daily while I might miss ping due to msg flooding.

**Pull request merged**
